/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://vikckmwpnrejtkcksndlian4sa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-y773wzw4gzduhm2osgcgmimegq",
    "aws_cognito_identity_pool_id": "us-east-1:2ff15a0f-d908-4b26-9c5a-85cabe52c20e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sxdViTk60",
    "aws_user_pools_web_client_id": "3pes8vtc1k1c91jatsn8qi2doo",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 7,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "quikyempresanuevo-storage-03418b58110747-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
